// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DiscordDataMirror.Dashboard.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ChannelBrowserFeature : object, global::Xunit.IClassFixture<ChannelBrowserFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Channel Browser", "    As a user\r\n    I want to browse channels in a Discord server\r\n    So that I c" +
                "an find and view specific channel messages", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ChannelBrowser.feature"
#line hidden
        
        public ChannelBrowserFeature(ChannelBrowserFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
    await testRunner.GivenAsync("the dashboard application is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("I am on a guild overview page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/ChannelBrowser.feature", @"Feature: Channel Browser
    As a user
    I want to browse channels in a Discord server
    So that I can find and view specific channel messages

Background:
    Given the dashboard application is running
    And I am on a guild overview page

@channels @smoke
Scenario: Channel browser displays categories and channels
    When I navigate to the channel browser
    Then I should see a list of channel categories
    And I should see channels within categories

@channels
Scenario: Clicking a channel shows channel details
    Given I am on the channel browser
    When I click on a channel
    Then I should see the channel details panel
    And I should see the ""View Messages"" button

@channels @navigation
Scenario: Clicking ""View Messages"" navigates to message viewer
    Given I am on the channel browser
    And I have selected a channel
    When I click the ""View Messages"" button
    Then I should be navigated to the message viewer
    And the URL should contain ""/channel/""

@channels @navigation
Scenario: Navigating between channels updates the view
    Given I am on the channel browser
    When I click on the first channel
    And I click on a different channel
    Then the channel details should update to the new channel

@channels
Scenario: Channel browser shows message counts
    When I navigate to the channel browser
    Then each channel should display a message count badge
", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/ChannelBrowser.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Channel Browser", "    As a user\r\n    I want to browse channels in a Discord server\r\n    So that I c" +
                        "an find and view specific channel messages", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard application is running", null, null, "a787ebb753607c5b9b58a9a0fb8ce69f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I am on a guild overview page", null, null, "1a31c20ac67e855f9b7cd5560feb50ce")}), "eb1fdd542925db5e95545ddc40cd9599"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(1)), "@channels", "d0aa31c931a92351a9752b15d0377abd"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(11)), "@smoke", "e8fd86b78964c65f8e6087bd9f4cd4e7")}), "Scenario", "Channel browser displays categories and channels", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the channel browser", null, null, "69da3552e3ac3e5386066d846cb1f8c2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see a list of channel categories", null, null, "e00b603dc984bc55a91735564b767462"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see channels within categories", null, null, "06cd946233a87558b5bb77d3c9054c10")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "a7435bcc4822e85ca0e67ed06b92c8c1")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(1)), "@channels", "f46a7a777805975c8cbb4a4864ea8bda")}), "Scenario", "Clicking a channel shows channel details", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am on the channel browser", null, null, "f98d12f97ea89c5e89419879c47d911d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click on a channel", null, null, "9e81a511ceb12c5f8e19b6b1e479a56c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see the channel details panel", null, null, "d6acf885f64c2b5c8aa987c84c649afb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see the \"View Messages\" button", null, null, "40d9e1eac9742f52abe6a22948efc907")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b2f8647647c8365aaf0692ebcce19b61")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(1)), "@channels", "1a31dbd1d2603951b602baca3f957e7f"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(11)), "@navigation", "63f135f9009bb150bce7175ec9328359")}), "Scenario", "Clicking \"View Messages\" navigates to message viewer", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am on the channel browser", null, null, "54201d084f5e325194ae1b9bc8d312a8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I have selected a channel", null, null, "46c51eb8a15ad35c8f9be946288af881"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click the \"View Messages\" button", null, null, "f0f238b41e31f35284255aa470f90160"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should be navigated to the message viewer", null, null, "edc471997397ed55a1d9078ac3c6865c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the URL should contain \"/channel/\"", null, null, "562beae956f7615d91140ec534072aec")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "41336514c1e895528e37d5fdf91554e8")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(1)), "@channels", "881528076ff80354a7f15a5d075a6169"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(11)), "@navigation", "d05fd9b9291e4c56a32f24160a67f08c")}), "Scenario", "Navigating between channels updates the view", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am on the channel browser", null, null, "2dd69672e9ea975b9d3ad27ab20ccb20"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click on the first channel", null, null, "d7f3d38b5576055cab85d68cc8615d57"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I click on a different channel", null, null, "39e02619e2af075d9ef258f5acceeefb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the channel details should update to the new channel", null, null, "02d863229230c95499a817ba61aaf130")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e752712315930b5d8fe7e2dec657351d")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(1)), "@channels", "775338cbec461255ba41b10e028f5df8")}), "Scenario", "Channel browser shows message counts", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the channel browser", null, null, "613bd13b2495d45db4fc5ba96635a134"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "each channel should display a message count badge", null, null, "1b951665b1329752855decb989a124fa")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3519f392e633c458881abaaf4d1c9770"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("e737e0752c24005faee134db46ffb51a", "Features/ChannelBrowser.feature", "Channel browser displays categories and channels", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a787ebb753607c5b9b58a9a0fb8ce69f"}), "444d1234ae73b452a6c8a1f9ca9cacdb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1a31c20ac67e855f9b7cd5560feb50ce"}), "ac2dac31866b635daddf8b73607bd0ad", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on a guild overview page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "69da3552e3ac3e5386066d846cb1f8c2"}), "4bfe298a4060bf53873f1a614c42295f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the channel browser"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e00b603dc984bc55a91735564b767462"}), "49678c3545e9a15e8141a6503959155c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see a list of channel categories"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "06cd946233a87558b5bb77d3c9054c10"}), "dd1155c7a9e84b5d815e2d2a5f863a73", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see channels within categories")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@channels", "d0aa31c931a92351a9752b15d0377abd"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "e8fd86b78964c65f8e6087bd9f4cd4e7")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a7435bcc4822e85ca0e67ed06b92c8c1"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("94b44585dce5ce5295393c34380edda1", "Features/ChannelBrowser.feature", "Clicking a channel shows channel details", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a787ebb753607c5b9b58a9a0fb8ce69f"}), "f469c67eb0359c5aa06a2062dbf43be5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1a31c20ac67e855f9b7cd5560feb50ce"}), "8897631098e58853b67b6691823aede1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on a guild overview page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f98d12f97ea89c5e89419879c47d911d"}), "4ed3f0033c079e579b6e3dc3eb45b426", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on the channel browser"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9e81a511ceb12c5f8e19b6b1e479a56c"}), "bcd65efb86134d5d83bae34519f26e1e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click on a channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d6acf885f64c2b5c8aa987c84c649afb"}), "ee68aa0bed303b5e8f1808a9e933433a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see the channel details panel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "40d9e1eac9742f52abe6a22948efc907"}), "aa26745b5bc8c55ea543943f5a81e5dc", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see the \"View Messages\" button")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@channels", "f46a7a777805975c8cbb4a4864ea8bda")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b2f8647647c8365aaf0692ebcce19b61"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("2ce1387d1d758d578d06b245589adba8", "Features/ChannelBrowser.feature", "Clicking \"View Messages\" navigates to message viewer", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a787ebb753607c5b9b58a9a0fb8ce69f"}), "7f676f137b39e25d983a92fb4d84dad5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1a31c20ac67e855f9b7cd5560feb50ce"}), "49d052b1bd5fdb55843e61077310f606", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on a guild overview page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "54201d084f5e325194ae1b9bc8d312a8"}), "34525ac62b480b51bd5bd8ef25a5d0a2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on the channel browser"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "46c51eb8a15ad35c8f9be946288af881"}), "7f4ddd4523713855b7b6898e18bd7c9a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I have selected a channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f0f238b41e31f35284255aa470f90160"}), "5411dfca1a248152b943c6f9a56be66a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click the \"View Messages\" button"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "edc471997397ed55a1d9078ac3c6865c"}), "ba67cb24ae76e85ea6b52fc96d609ff5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should be navigated to the message viewer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "562beae956f7615d91140ec534072aec"}), "c5eedfaa9feef858ae5ed5491db31a16", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the URL should contain \"/channel/\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@channels", "1a31dbd1d2603951b602baca3f957e7f"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@navigation", "63f135f9009bb150bce7175ec9328359")}), new System.Collections.Generic.List<string>(new string[] {
                                        "41336514c1e895528e37d5fdf91554e8"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3ed852bdaa577a5e94ed891c5c4debcd", "Features/ChannelBrowser.feature", "Navigating between channels updates the view", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a787ebb753607c5b9b58a9a0fb8ce69f"}), "679a026a44652c5c9a96197b8d2a4803", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1a31c20ac67e855f9b7cd5560feb50ce"}), "c0bbf454d770a8588df61a5d83809e28", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on a guild overview page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2dd69672e9ea975b9d3ad27ab20ccb20"}), "61b24efd3c257459ba5e163b396f3a66", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on the channel browser"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d7f3d38b5576055cab85d68cc8615d57"}), "3c22579d953d2e5b95d50ffb0c05931b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click on the first channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "39e02619e2af075d9ef258f5acceeefb"}), "99bab09697799c589064da29d4a787f3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click on a different channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "02d863229230c95499a817ba61aaf130"}), "63078182ee1b455bbaa9099fb7683811", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the channel details should update to the new channel")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@channels", "881528076ff80354a7f15a5d075a6169"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@navigation", "d05fd9b9291e4c56a32f24160a67f08c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e752712315930b5d8fe7e2dec657351d"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("fe915ee7293dde55bf10021b2d9290e0", "Features/ChannelBrowser.feature", "Channel browser shows message counts", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a787ebb753607c5b9b58a9a0fb8ce69f"}), "dfe6666e11e90153bb6cd5b5e25b18ef", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1a31c20ac67e855f9b7cd5560feb50ce"}), "d8bffb103b2be25da73bbb063d26e414", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on a guild overview page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "613bd13b2495d45db4fc5ba96635a134"}), "5dc63e713775555bb12ea89aeb4ab6d8", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the channel browser"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1b951665b1329752855decb989a124fa"}), "044f2bcf5dfca15bb82fe64aed553872", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "each channel should display a message count badge")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@channels", "775338cbec461255ba41b10e028f5df8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "3519f392e633c458881abaaf4d1c9770"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(ChannelBrowserFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(ChannelBrowserFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(ChannelBrowserFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Channel browser displays categories and channels")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Channel Browser")]
        [global::Xunit.TraitAttribute("Description", "Channel browser displays categories and channels")]
        [global::Xunit.TraitAttribute("Category", "channels")]
        [global::Xunit.TraitAttribute("Category", "smoke")]
        public async global::System.Threading.Tasks.Task ChannelBrowserDisplaysCategoriesAndChannels()
        {
            string[] tagsOfScenario = new string[] {
                    "channels",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Channel browser displays categories and channels", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("I navigate to the channel browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.ThenAsync("I should see a list of channel categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
    await testRunner.AndAsync("I should see channels within categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Clicking a channel shows channel details")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Channel Browser")]
        [global::Xunit.TraitAttribute("Description", "Clicking a channel shows channel details")]
        [global::Xunit.TraitAttribute("Category", "channels")]
        public async global::System.Threading.Tasks.Task ClickingAChannelShowsChannelDetails()
        {
            string[] tagsOfScenario = new string[] {
                    "channels"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clicking a channel shows channel details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.GivenAsync("I am on the channel browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
    await testRunner.WhenAsync("I click on a channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
    await testRunner.ThenAsync("I should see the channel details panel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
    await testRunner.AndAsync("I should see the \"View Messages\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Clicking \"View Messages\" navigates to message viewer")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Channel Browser")]
        [global::Xunit.TraitAttribute("Description", "Clicking \"View Messages\" navigates to message viewer")]
        [global::Xunit.TraitAttribute("Category", "channels")]
        [global::Xunit.TraitAttribute("Category", "navigation")]
        public async global::System.Threading.Tasks.Task ClickingViewMessagesNavigatesToMessageViewer()
        {
            string[] tagsOfScenario = new string[] {
                    "channels",
                    "navigation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clicking \"View Messages\" navigates to message viewer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("I am on the channel browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.AndAsync("I have selected a channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.WhenAsync("I click the \"View Messages\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.ThenAsync("I should be navigated to the message viewer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
    await testRunner.AndAsync("the URL should contain \"/channel/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Navigating between channels updates the view")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Channel Browser")]
        [global::Xunit.TraitAttribute("Description", "Navigating between channels updates the view")]
        [global::Xunit.TraitAttribute("Category", "channels")]
        [global::Xunit.TraitAttribute("Category", "navigation")]
        public async global::System.Threading.Tasks.Task NavigatingBetweenChannelsUpdatesTheView()
        {
            string[] tagsOfScenario = new string[] {
                    "channels",
                    "navigation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigating between channels updates the view", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.GivenAsync("I am on the channel browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
    await testRunner.WhenAsync("I click on the first channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.AndAsync("I click on a different channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.ThenAsync("the channel details should update to the new channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Channel browser shows message counts")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Channel Browser")]
        [global::Xunit.TraitAttribute("Description", "Channel browser shows message counts")]
        [global::Xunit.TraitAttribute("Category", "channels")]
        public async global::System.Threading.Tasks.Task ChannelBrowserShowsMessageCounts()
        {
            string[] tagsOfScenario = new string[] {
                    "channels"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Channel browser shows message counts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 40
    await testRunner.WhenAsync("I navigate to the channel browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("each channel should display a message count badge", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ChannelBrowserFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ChannelBrowserFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
