// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DiscordDataMirror.Dashboard.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MessageViewerFeature : object, global::Xunit.IClassFixture<MessageViewerFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Message Viewer", "    As a user\r\n    I want to view messages in a Discord channel\r\n    So that I ca" +
                "n read archived conversations", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MessageViewer.feature"
#line hidden
        
        public MessageViewerFeature(MessageViewerFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
    await testRunner.GivenAsync("the dashboard application is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/MessageViewer.feature", "Feature: Message Viewer\n    As a user\n    I want to view messages in a Discord ch" +
                    "annel\n    So that I can read archived conversations\n\nBackground:\n    Given the d" +
                    "ashboard application is running\n\n@messages @smoke\nScenario: Message viewer displ" +
                    "ays channel messages\n    Given I am viewing a channel with messages\n    Then I s" +
                    "hould see a list of message cards\n    And each message should display the author" +
                    " name\n    And each message should display the message content\n    And each messa" +
                    "ge should display a timestamp\n\n@messages\nScenario: Messages are grouped by autho" +
                    "r\n    Given I am viewing a channel with messages\n    Then consecutive messages f" +
                    "rom the same author should be grouped together\n\n@messages @navigation\nScenario: " +
                    "Breadcrumb navigation works\n    Given I am viewing a channel\n    Then I should s" +
                    "ee breadcrumb navigation\n    When I click on the guild name in the breadcrumb\n  " +
                    "  Then I should be navigated to the guild overview\n\n@messages @pagination\nScenar" +
                    "io: Loading older messages works\n    Given I am viewing a channel with many mess" +
                    "ages\n    When I click \"Load older messages\"\n    Then more messages should be dis" +
                    "played\n\n@messages @pagination\nScenario: Jumping to oldest messages works\n    Giv" +
                    "en I am viewing a channel\n    When I click the \"Oldest\" button\n    Then I should" +
                    " see the oldest messages in the channel\n\n@messages @pagination\nScenario: Jumping" +
                    " to newest messages works\n    Given I am viewing a channel at the oldest message" +
                    "s\n    When I click the \"Newest\" button\n    Then I should see the newest messages" +
                    " in the channel\n\n@messages @search\nScenario: Searching messages filters results\n" +
                    "    Given I am viewing a channel\n    When I enter a search term in the search fi" +
                    "eld\n    And I press Enter\n    Then only messages containing the search term shou" +
                    "ld be displayed\n\n@messages @navigation\nScenario: Navigating to a different chann" +
                    "el updates messages\n    Given I am viewing a channel\n    When I navigate to a di" +
                    "fferent channel using the URL\n    Then the messages should update to the new cha" +
                    "nnel\n    And the page title should update to the new channel name\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/MessageViewer.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Message Viewer", "    As a user\r\n    I want to view messages in a Discord channel\r\n    So that I ca" +
                        "n read archived conversations", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard application is running", null, null, "271be38aac95165c997f7cb11587f816")}), "381b892ae934d2599dd7e0ac0193e5e5"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(1)), "@messages", "c0200ef791abac56acfc2461959f1c74"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(11)), "@smoke", "f684d1226ad2415d945f80967b01975b")}), "Scenario", "Message viewer displays channel messages", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am viewing a channel with messages", null, null, "5fe5f41232c2d45eb40cfa5a4826d0d9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see a list of message cards", null, null, "dca4fd0785ab255b886f1725dbdc7dd1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "each message should display the author name", null, null, "30105c812fda365891b3be4718c3a1ae"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "each message should display the message content", null, null, "12060de5ff21bc5a9ace18f81c485435"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "each message should display a timestamp", null, null, "916636380239e05898a90d84a721053f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0e7da2a44c824459a6b3e8da556313b5")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(1)), "@messages", "a2cb94dc452f3f5189b44421a24b37f4")}), "Scenario", "Messages are grouped by author", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am viewing a channel with messages", null, null, "4b1a123e165df350a7f693f3806706a5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "consecutive messages from the same author should be grouped together", null, null, "0e4e4f587d3af059a647d0015f1a00aa")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "307f152ae4d2c8558bf3cbd1e365474e")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(1)), "@messages", "10ceb0d775c8965a8ea4e7332e244f4d"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(11)), "@navigation", "837ab29cbdd05f53ab6645f3d4d47c63")}), "Scenario", "Breadcrumb navigation works", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am viewing a channel", null, null, "5d30137ed34c8358bba93b1acd947450"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see breadcrumb navigation", null, null, "0bc9c1651239d05a8819c11311fc1739"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click on the guild name in the breadcrumb", null, null, "f58649f5c04c4450a970357a3b02ad75"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should be navigated to the guild overview", null, null, "34f5b30e85a8aa558d4aa15cf8759ae2")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "25773e33821b5d5da02ebdb462f0a1d2")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(1)), "@messages", "9667a2535ef82e569fed9b57dfc2560a"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(11)), "@pagination", "4c38a4f5cf587a5eb5491cc9535ffda4")}), "Scenario", "Loading older messages works", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am viewing a channel with many messages", null, null, "b75536555df21c59bc157798e25b2bbe"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click \"Load older messages\"", null, null, "9133a34c1b524d5088c3f3dc8a146b8d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "more messages should be displayed", null, null, "7fa4c607fe91665eb3e3c9e85c5de0de")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f33f66e9a12b6e52b4efe818f76bb213")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(1)), "@messages", "bb978d1fdb80d754bd9db8510a301611"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(11)), "@pagination", "91d4d98aa6d0b95184c712d6b2a92f5e")}), "Scenario", "Jumping to oldest messages works", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am viewing a channel", null, null, "b473d11b6c0ee35498503b5f337aa80c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click the \"Oldest\" button", null, null, "53aac4e65646a95c932c5970752b291d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see the oldest messages in the channel", null, null, "7e19baeb68fce45eb159f8c431141a67")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "9abe12c13e9b0d569c0572fcd988d460")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(1)), "@messages", "04c8fc416b93bc53830638109c66ceee"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(11)), "@pagination", "27b5e88884e1d05ea5c6a55390e796aa")}), "Scenario", "Jumping to newest messages works", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am viewing a channel at the oldest messages", null, null, "42a814bca0d96c5590af9639cd9bc8c0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click the \"Newest\" button", null, null, "0dbbb51511732e5ebbf80624ab8c9e51"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see the newest messages in the channel", null, null, "379a8196f8efa059b6ce52191519b3b6")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "69da51c387b1e859bab1d04017fda657")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(1)), "@messages", "e0a91aea37f9565fb48b51fa47b5cede"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(11)), "@search", "c21949a6f9b21d599570e4bd4d66a8e5")}), "Scenario", "Searching messages filters results", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am viewing a channel", null, null, "21a4f8e2cfb6895c90ed6e5bad62909b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I enter a search term in the search field", null, null, "a37e14713c251052b9b9c873831268de"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I press Enter", null, null, "19dddc7799420d59b259c9c3b1bda6fb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "only messages containing the search term should be displayed", null, null, "dceb37cbcf50495382c9cb67a26ced49")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ee9c97dff5d0745a9c1a391d646d07db")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(1)), "@messages", "db67cb354ccc7b5d8352c3513719f611"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(11)), "@navigation", "5f92e362660de7538460a271e4a3a41a")}), "Scenario", "Navigating to a different channel updates messages", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I am viewing a channel", null, null, "4ba7a41430f52550bc21c79ed79d62e8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to a different channel using the URL", null, null, "33303131c2cdab56ab346cb40f53cb99"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the messages should update to the new channel", null, null, "ac46db626583b950b0949a04a03b29ca"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(59, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the page title should update to the new channel name", null, null, "d3db3612104aa1538b93f44a42dc4d66")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "2041e3286ab1ee5c89c256cf9ecb0b7e"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("3ad13a6dca05d05fb64091833bfdf223", "Features/MessageViewer.feature", "Message viewer displays channel messages", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "271be38aac95165c997f7cb11587f816"}), "28fecf1db724bf599dc4d85f645cbde3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5fe5f41232c2d45eb40cfa5a4826d0d9"}), "be7f100043eee95bb34894b4649148d2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am viewing a channel with messages"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "dca4fd0785ab255b886f1725dbdc7dd1"}), "3e64b47bb49e1a5db6ce9e781f6bee76", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see a list of message cards"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "30105c812fda365891b3be4718c3a1ae"}), "de8e49e92751255f9109075507149711", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "each message should display the author name"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "12060de5ff21bc5a9ace18f81c485435"}), "076da5474973ba5d8bbdb74b0e7d329f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "each message should display the message content"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "916636380239e05898a90d84a721053f"}), "42cf1faf1b8cfe5d97726742b0a22e4d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "each message should display a timestamp")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@messages", "c0200ef791abac56acfc2461959f1c74"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@smoke", "f684d1226ad2415d945f80967b01975b")}), new System.Collections.Generic.List<string>(new string[] {
                                        "0e7da2a44c824459a6b3e8da556313b5"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("92f2337361733f569085e620a8a42bf5", "Features/MessageViewer.feature", "Messages are grouped by author", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "271be38aac95165c997f7cb11587f816"}), "559505c31f4d49589ced0604802e1200", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4b1a123e165df350a7f693f3806706a5"}), "9c7f021ee77ff8558237349bcd982033", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am viewing a channel with messages"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0e4e4f587d3af059a647d0015f1a00aa"}), "20245c3fb6807a5296bb933f04fa093c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "consecutive messages from the same author should be grouped together")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@messages", "a2cb94dc452f3f5189b44421a24b37f4")}), new System.Collections.Generic.List<string>(new string[] {
                                        "307f152ae4d2c8558bf3cbd1e365474e"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("9c5695a9c80b5c51b937b0e07d70ab2f", "Features/MessageViewer.feature", "Breadcrumb navigation works", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "271be38aac95165c997f7cb11587f816"}), "d370e5d2e547545cb8de41934b8c1cc8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5d30137ed34c8358bba93b1acd947450"}), "3706281681cd855db965537b61f7300e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am viewing a channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0bc9c1651239d05a8819c11311fc1739"}), "cb9717cd014f625795da87c76acfd710", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see breadcrumb navigation"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f58649f5c04c4450a970357a3b02ad75"}), "a0dcddbce70c385e8d6171534a0204e0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click on the guild name in the breadcrumb"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "34f5b30e85a8aa558d4aa15cf8759ae2"}), "867f3b592a5db45fae9a7c68becd09d8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should be navigated to the guild overview")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@messages", "10ceb0d775c8965a8ea4e7332e244f4d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@navigation", "837ab29cbdd05f53ab6645f3d4d47c63")}), new System.Collections.Generic.List<string>(new string[] {
                                        "25773e33821b5d5da02ebdb462f0a1d2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("008d4abd3e4e345ba5f0c986035474b0", "Features/MessageViewer.feature", "Loading older messages works", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "271be38aac95165c997f7cb11587f816"}), "e44dcdb85c8d8e5eae63c7c7a3c78b2d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b75536555df21c59bc157798e25b2bbe"}), "dff6e6d3d5b02d53bb8ec36434222b6a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am viewing a channel with many messages"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9133a34c1b524d5088c3f3dc8a146b8d"}), "168bf54bd6685553a6e341a320190f9e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click \"Load older messages\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7fa4c607fe91665eb3e3c9e85c5de0de"}), "a4932cdbe222755a9f92aa093b6ebae7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "more messages should be displayed")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@messages", "9667a2535ef82e569fed9b57dfc2560a"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pagination", "4c38a4f5cf587a5eb5491cc9535ffda4")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f33f66e9a12b6e52b4efe818f76bb213"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("9caf48c6f95fe15f8c0376c194dfc9ca", "Features/MessageViewer.feature", "Jumping to oldest messages works", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "271be38aac95165c997f7cb11587f816"}), "857423c2bd45c95ea6cc868f7ab33520", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b473d11b6c0ee35498503b5f337aa80c"}), "cf4867b6d669f15799a7f59e00f4cf72", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am viewing a channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "53aac4e65646a95c932c5970752b291d"}), "70e769165d11745aa404a84e3dc7b694", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click the \"Oldest\" button"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7e19baeb68fce45eb159f8c431141a67"}), "8b448b1219f6d6538a5acc05e1d89353", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see the oldest messages in the channel")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@messages", "bb978d1fdb80d754bd9db8510a301611"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pagination", "91d4d98aa6d0b95184c712d6b2a92f5e")}), new System.Collections.Generic.List<string>(new string[] {
                                        "9abe12c13e9b0d569c0572fcd988d460"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("a42296af5ba47a5a828453295a962e87", "Features/MessageViewer.feature", "Jumping to newest messages works", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "271be38aac95165c997f7cb11587f816"}), "ddb5e860ffde715a90f9391ee8d35353", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42a814bca0d96c5590af9639cd9bc8c0"}), "aae8504ba07df25e967ad3eb9044f660", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am viewing a channel at the oldest messages"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0dbbb51511732e5ebbf80624ab8c9e51"}), "f6a643c1e64e0d5cbd3bb711a06dc727", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click the \"Newest\" button"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "379a8196f8efa059b6ce52191519b3b6"}), "cf51c08633143256a2d15b1246058822", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see the newest messages in the channel")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@messages", "04c8fc416b93bc53830638109c66ceee"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@pagination", "27b5e88884e1d05ea5c6a55390e796aa")}), new System.Collections.Generic.List<string>(new string[] {
                                        "69da51c387b1e859bab1d04017fda657"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("bf290e6607e1d657922ec48b9398ec57", "Features/MessageViewer.feature", "Searching messages filters results", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "271be38aac95165c997f7cb11587f816"}), "e256dc58e02b8a56b96f2c88c8329653", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "21a4f8e2cfb6895c90ed6e5bad62909b"}), "02f7f7bf07073053b894fe9a6abbbeb7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am viewing a channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a37e14713c251052b9b9c873831268de"}), "cd6f4deb1fd3d55fb522c8bcc3faebcc", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I enter a search term in the search field"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "19dddc7799420d59b259c9c3b1bda6fb"}), "bdb7dbea0281ba52ae40184bfd9470f5", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I press Enter"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "dceb37cbcf50495382c9cb67a26ced49"}), "f113028fc0aa1655882da6b95146a948", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "only messages containing the search term should be displayed")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@messages", "e0a91aea37f9565fb48b51fa47b5cede"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@search", "c21949a6f9b21d599570e4bd4d66a8e5")}), new System.Collections.Generic.List<string>(new string[] {
                                        "ee9c97dff5d0745a9c1a391d646d07db"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("78f39f1a586d9853a8775cb686437bf7", "Features/MessageViewer.feature", "Navigating to a different channel updates messages", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "271be38aac95165c997f7cb11587f816"}), "c9f668b96e27e15bbedc76d01a8d396a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard application is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4ba7a41430f52550bc21c79ed79d62e8"}), "ebc1bb2203bd8f5f85a1cd9d7ca2326b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am viewing a channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "33303131c2cdab56ab346cb40f53cb99"}), "afe1d21093791051a034d46ad3c94593", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to a different channel using the URL"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ac46db626583b950b0949a04a03b29ca"}), "6ed3133d03918156895f7f8a6b8aba81", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the messages should update to the new channel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d3db3612104aa1538b93f44a42dc4d66"}), "5ebd6d45156bed548fe5062c10906044", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the page title should update to the new channel name")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@messages", "db67cb354ccc7b5d8352c3513719f611"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@navigation", "5f92e362660de7538460a271e4a3a41a")}), new System.Collections.Generic.List<string>(new string[] {
                                        "2041e3286ab1ee5c89c256cf9ecb0b7e"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(MessageViewerFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(MessageViewerFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(MessageViewerFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Message viewer displays channel messages")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Message Viewer")]
        [global::Xunit.TraitAttribute("Description", "Message viewer displays channel messages")]
        [global::Xunit.TraitAttribute("Category", "messages")]
        [global::Xunit.TraitAttribute("Category", "smoke")]
        public async global::System.Threading.Tasks.Task MessageViewerDisplaysChannelMessages()
        {
            string[] tagsOfScenario = new string[] {
                    "messages",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Message viewer displays channel messages", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 11
    await testRunner.GivenAsync("I am viewing a channel with messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
    await testRunner.ThenAsync("I should see a list of message cards", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("each message should display the author name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync("each message should display the message content", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("each message should display a timestamp", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Messages are grouped by author")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Message Viewer")]
        [global::Xunit.TraitAttribute("Description", "Messages are grouped by author")]
        [global::Xunit.TraitAttribute("Category", "messages")]
        public async global::System.Threading.Tasks.Task MessagesAreGroupedByAuthor()
        {
            string[] tagsOfScenario = new string[] {
                    "messages"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Messages are grouped by author", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("I am viewing a channel with messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.ThenAsync("consecutive messages from the same author should be grouped together", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Breadcrumb navigation works")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Message Viewer")]
        [global::Xunit.TraitAttribute("Description", "Breadcrumb navigation works")]
        [global::Xunit.TraitAttribute("Category", "messages")]
        [global::Xunit.TraitAttribute("Category", "navigation")]
        public async global::System.Threading.Tasks.Task BreadcrumbNavigationWorks()
        {
            string[] tagsOfScenario = new string[] {
                    "messages",
                    "navigation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Breadcrumb navigation works", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.GivenAsync("I am viewing a channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.ThenAsync("I should see breadcrumb navigation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
    await testRunner.WhenAsync("I click on the guild name in the breadcrumb", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("I should be navigated to the guild overview", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Loading older messages works")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Message Viewer")]
        [global::Xunit.TraitAttribute("Description", "Loading older messages works")]
        [global::Xunit.TraitAttribute("Category", "messages")]
        [global::Xunit.TraitAttribute("Category", "pagination")]
        public async global::System.Threading.Tasks.Task LoadingOlderMessagesWorks()
        {
            string[] tagsOfScenario = new string[] {
                    "messages",
                    "pagination"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Loading older messages works", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.GivenAsync("I am viewing a channel with many messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.WhenAsync("I click \"Load older messages\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.ThenAsync("more messages should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Jumping to oldest messages works")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Message Viewer")]
        [global::Xunit.TraitAttribute("Description", "Jumping to oldest messages works")]
        [global::Xunit.TraitAttribute("Category", "messages")]
        [global::Xunit.TraitAttribute("Category", "pagination")]
        public async global::System.Threading.Tasks.Task JumpingToOldestMessagesWorks()
        {
            string[] tagsOfScenario = new string[] {
                    "messages",
                    "pagination"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Jumping to oldest messages works", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 37
    await testRunner.GivenAsync("I am viewing a channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
    await testRunner.WhenAsync("I click the \"Oldest\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("I should see the oldest messages in the channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Jumping to newest messages works")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Message Viewer")]
        [global::Xunit.TraitAttribute("Description", "Jumping to newest messages works")]
        [global::Xunit.TraitAttribute("Category", "messages")]
        [global::Xunit.TraitAttribute("Category", "pagination")]
        public async global::System.Threading.Tasks.Task JumpingToNewestMessagesWorks()
        {
            string[] tagsOfScenario = new string[] {
                    "messages",
                    "pagination"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Jumping to newest messages works", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 43
    await testRunner.GivenAsync("I am viewing a channel at the oldest messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
    await testRunner.WhenAsync("I click the \"Newest\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("I should see the newest messages in the channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Searching messages filters results")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Message Viewer")]
        [global::Xunit.TraitAttribute("Description", "Searching messages filters results")]
        [global::Xunit.TraitAttribute("Category", "messages")]
        [global::Xunit.TraitAttribute("Category", "search")]
        public async global::System.Threading.Tasks.Task SearchingMessagesFiltersResults()
        {
            string[] tagsOfScenario = new string[] {
                    "messages",
                    "search"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Searching messages filters results", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 49
    await testRunner.GivenAsync("I am viewing a channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
    await testRunner.WhenAsync("I enter a search term in the search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
    await testRunner.AndAsync("I press Enter", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.ThenAsync("only messages containing the search term should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Navigating to a different channel updates messages")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Message Viewer")]
        [global::Xunit.TraitAttribute("Description", "Navigating to a different channel updates messages")]
        [global::Xunit.TraitAttribute("Category", "messages")]
        [global::Xunit.TraitAttribute("Category", "navigation")]
        public async global::System.Threading.Tasks.Task NavigatingToADifferentChannelUpdatesMessages()
        {
            string[] tagsOfScenario = new string[] {
                    "messages",
                    "navigation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigating to a different channel updates messages", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 56
    await testRunner.GivenAsync("I am viewing a channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
    await testRunner.WhenAsync("I navigate to a different channel using the URL", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("the messages should update to the new channel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
    await testRunner.AndAsync("the page title should update to the new channel name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MessageViewerFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MessageViewerFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
